name: Build EXE

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    env:
      APP_DIR: ekj_checker

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Show files (debug)
        run: |
          dir
          dir ${{ env.APP_DIR }}

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build exe
        run: |
          pyinstaller --onefile --name ekj_checker --distpath .\dist --workpath .\build --specpath .\build .\${{ env.APP_DIR }}\main.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ekj-checker-exe
          path: |
            dist/ekj_checker.exe
            ${{ env.APP_DIR }}/run_checker.bat
            ${{ env.APP_DIR }}/config.toml
