- name: Build exe
  run: |
    pyinstaller --onefile --name ekj_checker --distpath .\dist --workpath .\build --specpath .\build .\ekj_checker\main.py

- name: Upload artifact
  uses: actions/upload-artifact@v4
  with:
    name: ekj-checker-exe
    path: |
      dist/ekj_checker.exe
      ekj_checker/run_checker.bat
      ekj_checker/config.toml
